SELECT * FROM AIR

SELECT * FROM AIR WHERE IATA_CODE IS NULL
SELECT * FROM AIR WHERE AIRLINE_NAME IS NULL
SELECT * FROM AIR WHERE REGION IS NULL
SELECT * FROM AIR WHERE FUNCTIONAL_CURRENCY IS NULL
SELECT * FROM AIR WHERE EBIT_USD IS NULL
SELECT * FROM AIR WHERE LOAD_FACTOR IS NULL
SELECT * FROM AIR WHERE LOW_COST_CARRIER IS NULL
SELECT * FROM AIR WHERE AIRLINE_AGE IS NULL
SELECT * FROM AIR WHERE NUM_ROUTES IS NULL
SELECT * FROM AIR WHERE PASSENGER_YIELD IS NULL
SELECT * FROM AIR WHERE ASK IS NULL
SELECT * FROM AIR WHERE AVG_FLEET_AGE IS NULL
SELECT * FROM AIR WHERE FLEET_SIZE IS NULL
SELECT * FROM AIR WHERE AIRCRAFT_UTILISATION IS NULL;

SELECT LOW_COST_CARRIER, AVG (EBIT_USD) FROM AIR WHERE EBIT_USD IS NOT NULL
GROUP BY LOW_COST_CARRIER;

SELECT * FROM AIR;



SELECT LOW_COST_CARRIER, AVG_FLEET_AGE, CASE WHEN AVG_FLEET_AGE <= AVG_AGE THEN
FROM AIR;
